// File: src/test/java/com/budgetTracker/repository/UserRepositoryTest.java

package com.budgetTracker.repository;

import com.budgetTracker.model.entity.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests
 *
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private TestEntityManager entityManager; // Tool to set up data directly in the database

    private User testUser;
    private final String TEST_USERNAME = "testuser";
    private final String TEST_PASSWORD = "$2a$10$UcGfIQRv0REOf2R5ppaIYufAURQE8RNxHHTRcrh3QSh1yuSXtVy92";

    @BeforeEach
    void setup() {
        // Create a user entity for testing
        testUser = new User();
        testUser.setUsername(TEST_USERNAME);
        testUser.setPasswordHash(TEST_PASSWORD);
        testUser.setEmail("test@example.com"); // Assuming email is a required field

        // Persist the user to the in-memory database
        entityManager.persistAndFlush(testUser);
        entityManager.flush();
        entityManager.clear();
    }

    // --- 1. Custom Finder Method Tests ---

    @Test
    void findByUsername_shouldReturnUser_whenUserExists() {
        // Act
        Optional<User> foundUser = userRepository.findByUsername(TEST_USERNAME);

        // Assert
        assertThat(foundUser).isPresent();
        assertThat(foundUser.get().getUsername()).isEqualTo(TEST_USERNAME);
        assertThat(foundUser.get().getPasswordHash()).isEqualTo(TEST_PASSWORD);
        assertThat(foundUser.get().getId()).isNotNull();
    }

    @Test
    void findByUsername_shouldReturnEmptyOptional_whenUserDoesNotExist() {
        // Act
        Optional<User> foundUser = userRepository.findByUsername("nonexistent");

        // Assert
        assertThat(foundUser).isEmpty();
    }

    // --- 2. JpaRepository Methods Test (Sanity Check) ---
    @Test
    void findById_shouldReturnUser_whenIdExists() {
        // Arrange: Use the ID generated by the setup
        Long userId = testUser.getId();

        // Act
        Optional<User> foundUser = userRepository.findById(userId);

        // Assert
        assertThat(foundUser).isPresent();
        //assertThat(foundUser.get().getId()).isEqualTo(userId);
    }
}